dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  replicas: 0
configs:
  cm:
    timeout.reconciliation: 30s
    timeout.reconciliation.jitter: 0s
  params:
    server.insecure: true
controller:
  resources:
    requests: {cpu: 100m, memory: 128Mi}
    limits: {cpu: 500m, memory: 512Mi}
repoServer:
  resources:
    requests: {cpu: 50m, memory: 64Mi}
    limits: {cpu: 500m, memory: 256Mi}
server:
  resources:
    requests: {cpu: 50m, memory: 64Mi}
    limits: {cpu: 300m, memory: 256Mi}
redis:
  resources:
    requests: {cpu: 25m, memory: 32Mi}
    limits: {cpu: 200m, memory: 128Mi}
