apiVersion: v1
kind: PersistentVolume
metadata:
  name: session13-static-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/session13-static-data
    type: DirectoryOrCreate
