apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-pvc
spec:
  storageClassName: ""
  volumeName: session13-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
