apiVersion: v1
kind: ConfigMap
metadata:
  name: labledger-settings
  annotations: {argocd.argoproj.io/sync-wave: "0"}
data:
  APP_NAME: LabLedger API
  APP_VERSION: {{ .Values.backend.tag | quote }}
