apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  ENVIRONMENT: {{ .Values.app.environment | quote }}
  index.html: |
    <h1>{{ .Values.app.name }} {{ .Values.app.version }}</h1>
    <p>Environment: {{ .Values.app.environment }}</p>
